"use client";
import './globals.css'
import { SessionProvider } from "next-auth/react"

export const metadata = {
  title: 'Equality Mastermind',
  description: 'Generated by create next app and proexidno',
}

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className=''>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
