"use client";
import Navbar from './components/navbar'
import './globals.css'
import { SessionProvider } from "next-auth/react"

export const metadata = {
  title: 'Equality Mastermind',
  description: 'Generated by create next app and proexidno',
}

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className='sm:text-lg md:text-xl font-bold lg:text-2xl xl:text-3xl'>
        <SessionProvider session={session}>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
